# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/rundown/main.go
    ldflags:
      - -s -w -X main.GitCommit={{ .Commit }} -X main.Version={{ .Version }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: rundown
    tap:
      owner: elseano
      name: homebrew-taps
    commit_author:
      name: Sean St. Quentin
      email: sean.stquentin@gmail.com
    folder: Formula
    homepage: "https://github.com/elseano/rundown"
    description: "Rundown runs Markdown files, making them powerful and pretty console applications"
    license: "MIT"
    test: |
      assert_match "rundown version #{version}", shell_output("#{bin}/rundown --version")
    install: |
      bin.install "rundown"
      
      output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "bash")
      (bash_completion/"rundown").write output

      output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "zsh")
      (zsh_completion/"rundown").write output

      output = Utils.safe_popen_read("#{bin}/rundown", "--completions", "fish")
      (fish_completion/"rundown").write output

